export enum GameState {
  LOADING = 'LOADING',
  MAIN_MENU = 'MAIN_MENU',
  PLAYING = 'PLAYING',
  PAUSED = 'PAUSED',
  INVENTORY = 'INVENTORY',
  SETTINGS = 'SETTINGS',
  CUTSCENE = 'CUTSCENE',
  DEAD = 'DEAD',
  ENDING = 'ENDING',
}
